// Package seed provides realistic, category-specific post and comment
// templates for the "realistic" seed preset so each sanctum feels on-topic.
package seed

// RealisticPostTemplate defines one post plus its comments for seeding.
type RealisticPostTemplate struct {
	Title     string
	Content   string
	PostType  string
	ImageSeed string // used for picsum.photos/seed/ImageSeed/800/600
	LinkURL   string
	YoutubeID string
	Comments  []string
}

// realisticTemplatesBySanctum maps sanctum slug to a slice of post templates.
// ImageSeed is used as https://picsum.photos/seed/<ImageSeed>/800/600 for relevance.
var realisticTemplatesBySanctum = map[string][]RealisticPostTemplate{
	"general": {
		{
			Title:     "What made you join Sanctum?",
			Content:   "Just curious what drew everyone here. I was looking for smaller communities where discussions don’t get lost in the noise.",
			PostType:  "text",
			ImageSeed: "general-welcome",
			Comments:  []string{"Same here, tired of algorithm-driven feeds.", "Came for the hobby sanctums.", "Friend invited me and I stayed."},
		},
		{
			Title:     "Best way to discover new sanctums?",
			Content:   "Aside from the main list—how do you usually find sanctums that match your interests?",
			PostType:  "text",
			ImageSeed: "general-discover",
			Comments:  []string{"I browse by category then read a few posts.", "Check the sidebar on posts I like.", "Search for keywords."},
		},
	},
	"herald": {
		{
			Title:     "New feature: sanctum-specific feeds",
			Content:   "You can now subscribe to individual sanctums and see only those posts in your feed. Check Settings > Feed to customize.",
			PostType:  "text",
			ImageSeed: "herald-feature",
			Comments:  []string{"Nice, been waiting for this!", "Works great so far.", "Thanks team."},
		},
	},
	"support": {
		{
			Title:     "How do I reset my password?",
			Content:   "I don’t see a “Forgot password” link on the login page. Am I missing it?",
			PostType:  "text",
			ImageSeed: "support-help",
			Comments:  []string{"It’s under the login form—small link.", "If you still don’t see it, contact support@sanctum.example.com."},
		},
	},
	"movies": {
		{
			Title:     "Dune Part Two — worth seeing in IMAX?",
			Content:   "Trying to decide if I should drive to the IMAX screen or just catch it at the local theater. Heard the sound design is insane.",
			PostType:  "text",
			ImageSeed: "movies-dune",
			Comments:  []string{"IMAX 100%. The scale is made for it.", "Saw it in IMAX twice. Do it.", "Local is fine if you have good sound."},
		},
		{
			Title:     "Underrated sci-fi from the last 5 years?",
			Content:   "Looking for something that flew under the radar. Already saw Arrival, Blade Runner 2049, and Dune.",
			PostType:  "text",
			ImageSeed: "movies-scifi",
			Comments:  []string{"High Life (2018) is weird and great.", "Prospect (2018) with Pedro Pascal.", "Aniara if you like bleak."},
		},
		{
			Title:     "Just rewatched The Godfather",
			Content:   "First time in years. Still holds up. That baptism scene is still one of the best cuts in cinema.",
			PostType:  "media",
			ImageSeed: "movies-godfather",
			Comments:  []string{"The editing in that sequence is unreal.", "Coppola at his peak.", "Never gets old."},
		},
		{
			Title:     "Best horror movie for someone who doesn’t like jump scares?",
			Content:   "I prefer dread and atmosphere over cheap jumps. Recommendations?",
			PostType:  "text",
			ImageSeed: "movies-horror",
			Comments:  []string{"The Witch, Hereditary, It Follows.", "Session 9 is all atmosphere.", "The Shining if you haven’t."},
		},
		{
			Title:     "Official trailer for the new Nolan film",
			Content:   "Trailer just dropped. Thoughts?",
			PostType:  "link",
			ImageSeed: "movies-trailer",
			LinkURL:   "https://www.youtube.com/results?search_query=nolan+film+trailer",
			Comments:  []string{"Hype.", "Looks visually stunning as always.", "Day one."},
		},
		{
			Title:     "What’s the one movie you always recommend?",
			Content:   "Mine is Children of Men. What’s yours?",
			PostType:  "text",
			ImageSeed: "movies-recommend",
			Comments:  []string{"Eternal Sunshine.", "Spirited Away.", "The Fall (2006)."},
		},
		{
			Title:     "Rewatch ranking: Lord of the Rings extended vs theatrical",
			Content:   "Do you go extended for the full experience or theatrical for pacing?",
			PostType:  "text",
			ImageSeed: "movies-lotr",
			Comments:  []string{"Extended every time.", "Theatrical for first watch, extended for rewatches.", "Extended Fellowship, theatrical for the other two."},
		},
		{
			Title:     "Foreign language films that don’t feel like homework",
			Content:   "Looking for accessible non-English films—thriller, drama, or comedy.",
			PostType:  "text",
			ImageSeed: "movies-foreign",
			Comments:  []string{"Parasite, Amélie, Crouching Tiger.", "The Lives of Others.", "Train to Busan."},
		},
		{
			Title:     "Movie that made you cry (no shame)",
			Content:   "I’ll go first: Coco. That ending gets me every time.",
			PostType:  "text",
			ImageSeed: "movies-cry",
			Comments:  []string{"Grave of the Fireflies.", "Aftersun.", "Same, Coco."},
		},
		{
			Title:     "Best cinematography in a film you’ve seen recently?",
			Content:   "Just watched The Batman—Greig Fraser’s work is stunning. What else has blown you away lately?",
			PostType:  "text",
			ImageSeed: "movies-cinema",
			Comments:  []string{"Dune Part Two, obviously.", "The Northman.", "Decision to Leave."},
		},
	},
	"television": {
		{
			Title:     "Severance finale — what did you think?",
			Content:   "No spoilers but that last shot. Need season 2 ASAP.",
			PostType:  "text",
			ImageSeed: "tv-severance",
			Comments:  []string{"Same. That cliffhanger hurt.", "Best show in years.", "Already rewatching."},
		},
		{
			Title:     "Underrated show that got cancelled too soon",
			Content:   "Mine: The OA. Still not over it.",
			PostType:  "text",
			ImageSeed: "tv-cancelled",
			Comments:  []string{"Firefly, always.", "Mindhunter.", "Santa Clarita Diet."},
		},
		{
			Title:     "Best limited series you’ve seen?",
			Content:   "Looking for something I can finish in a weekend. Prefer thriller or drama.",
			PostType:  "text",
			ImageSeed: "tv-limited",
			Comments:  []string{"Mare of Easttown.", "The Queen’s Gambit.", "The Night Of."},
		},
		{
			Title:     "Comfort rewatch when you’re sick?",
			Content:   "I always go The Office or Parks and Rec. What’s yours?",
			PostType:  "text",
			ImageSeed: "tv-comfort",
			Comments:  []string{"Brooklyn Nine-Nine.", "Schitt’s Creek.", "Frasier."},
		},
		{
			Title:     "New season of The Bear is out",
			Content:   "No spoilers—just finished episode 1. Already stressed.",
			PostType:  "text",
			ImageSeed: "tv-bear",
			Comments:  []string{"Yes chef.", "The pacing is insane.", "Best show on TV."},
		},
		{
			Title:     "Show with the best series finale?",
			Content:   "So many shows fumble the ending. Which ones stuck the landing?",
			PostType:  "text",
			ImageSeed: "tv-finale",
			Comments:  []string{"The Good Place.", "Six Feet Under.", "Breaking Bad."},
		},
		{
			Title:     "Recommend a 10-episode-or-less show",
			Content:   "Short flight tomorrow, need something tight and bingeable.",
			PostType:  "text",
			ImageSeed: "tv-short",
			Comments:  []string{"Chernobyl.", "Fleabag.", "Band of Brothers."},
		},
		{
			Title:     "True Detective S4 — worth it?",
			Content:   "Loved S1, skipped 2 and 3. Heard mixed things about Night Country.",
			PostType:  "text",
			ImageSeed: "tv-td",
			Comments:  []string{"Yes, way better than 2 and 3.", "Atmosphere is great, ending is divisive.", "Worth a watch."},
		},
		{
			Title:     "Best animated show for adults?",
			Content:   "Already love BoJack and Arcane. What else?",
			PostType:  "text",
			ImageSeed: "tv-animated",
			Comments:  []string{"Invincible.", "Blue Eye Samurai.", "Undone."},
		},
		{
			Title:     "Documentary series recommendations",
			Content:   "Loved Making a Murderer and The Staircase. What’s next?",
			PostType:  "text",
			ImageSeed: "tv-docs",
			Comments:  []string{"Wild Wild Country.", "The Jinx.", "American Vandal (mockumentary but great)."},
		},
	},
	"books": {
		{
			Title:     "Just finished Project Hail Mary",
			Content:   "No spoilers but Rocky might be my favorite character in any book. What did you think?",
			PostType:  "text",
			ImageSeed: "books-phm",
			Comments:  []string{"Rocky is the best.", "Loved it more than The Martian.", "Audiobook is incredible."},
		},
		{
			Title:     "Recommend a book that feels like a warm blanket",
			Content:   "Going through a rough patch. Need something cozy and hopeful.",
			PostType:  "text",
			ImageSeed: "books-cozy",
			Comments:  []string{"The House in the Cerulean Sea.", "A Psalm for the Wild-Built.", "Legends & Lattes."},
		},
		{
			Title:     "Best fantasy series to get lost in?",
			Content:   "Looking for something long and immersive. Already read Sanderson and Malazan.",
			PostType:  "text",
			ImageSeed: "books-fantasy",
			Comments:  []string{"Wheel of Time.", "Realm of the Elderlings.", "First Law trilogy."},
		},
		{
			Title:     "Non-fiction that reads like a thriller",
			Content:   "Loved Killers of the Flower Moon and Bad Blood. What’s next?",
			PostType:  "text",
			ImageSeed: "books-nf",
			Comments:  []string{"The Devil in the White City.", "Empire of Pain.", "Say Nothing."},
		},
		{
			Title:     "Dune — read before watching the movie?",
			Content:   "Planning to see Dune Part Two. Should I read the book first or go in blind?",
			PostType:  "text",
			ImageSeed: "books-dune",
			Comments:  []string{"Movie stands alone but book adds a lot.", "Read after—you’ll appreciate the adaptation.", "Either way works."},
		},
		{
			Title:     "Favorite short story collection?",
			Content:   "I have 20 minutes before bed most nights. Prefer short stories over starting a novel.",
			PostType:  "text",
			ImageSeed: "books-short",
			Comments:  []string{"Exhalation by Ted Chiang.", "Stories of Your Life and Others.", "Her Body and Other Parties."},
		},
		{
			Title:     "Book that changed how you think about something",
			Content:   "Mine: Sapiens. What’s yours?",
			PostType:  "text",
			ImageSeed: "books-mindset",
			Comments:  []string{"Thinking, Fast and Slow.", "The Righteous Mind.", "Meditations."},
		},
		{
			Title:     "Best audiobook narrator you’ve heard?",
			Content:   "Some narrators elevate the book. Who’s your favorite?",
			PostType:  "text",
			ImageSeed: "books-audio",
			Comments:  []string{"Steven Pacey (First Law).", "Ray Porter (Project Hail Mary).", "Julia Whelan."},
		},
		{
			Title:     "Re-reading The Hobbit as an adult",
			Content:   "Haven’t read it since middle school. The tone is so different from LotR—more fairy tale. Loving it.",
			PostType:  "text",
			ImageSeed: "books-hobbit",
			Comments:  []string{"It was written for his kids!", "So cozy.", "Riddles in the Dark still holds up."},
		},
		{
			Title:     "Book club pick for a mixed group?",
			Content:   "Need something that sparks discussion but isn’t too heavy. 5 people, varied tastes.",
			PostType:  "text",
			ImageSeed: "books-club",
			Comments:  []string{"Remarkably Bright Creatures.", "Lessons in Chemistry.", "The Thursday Murder Club."},
		},
	},
	"music": {
		{
			Title:     "What are you listening to this week?",
			Content:   "I’ve had the new Vampire Weekend album on repeat. Curious what’s in everyone else’s rotation.",
			PostType:  "text",
			ImageSeed: "music-week",
			Comments:  []string{"New Charli XCX.", "Getting into JPEGMAFIA.", "Revisiting Radiohead."},
		},
		{
			Title:     "Best album to listen to start-to-finish?",
			Content:   "No skips. Cohesive experience. What’s your pick?",
			PostType:  "text",
			ImageSeed: "music-album",
			Comments:  []string{"To Pimp a Butterfly.", "Blonde.", "Abbey Road."},
		},
		{
			Title:     "Underrated artist that deserves more attention",
			Content:   "Mine: Nilüfer Yanya. Incredible songwriting and production.",
			PostType:  "text",
			ImageSeed: "music-underrated",
			Comments:  []string{"Big Thief.", "Japanese Breakfast.", "Weyes Blood."},
		},
		{
			Title:     "Concert you’re most looking forward to in 2025?",
			Content:   "Just got tickets for the National. What’s on your calendar?",
			PostType:  "text",
			ImageSeed: "music-concert",
			Comments:  []string{"Seeing Beyoncé again.", "Phoebe Bridgers.", "LCD Soundsystem."},
		},
		{
			Title:     "Best headphones for listening to albums at home?",
			Content:   "Budget around $200. Prefer over-ear, wired. What do you use?",
			PostType:  "text",
			ImageSeed: "music-headphones",
			Comments:  []string{"Sennheiser HD 560S.", "Beyerdynamic DT 770.", "Audio-Technica ATH-M50x."},
		},
		{
			Title:     "Song that always puts you in a good mood",
			Content:   "Mine: September by Earth, Wind & Fire. Impossible to be sad.",
			PostType:  "text",
			ImageSeed: "music-mood",
			Comments:  []string{"Dancing Queen.", "Mr. Blue Sky.", "Float On by Modest Mouse."},
		},
		{
			Title:     "Recommend something similar to Bon Iver",
			Content:   "Love the atmospheric, layered sound. What else scratches that itch?",
			PostType:  "text",
			ImageSeed: "music-boniver",
			Comments:  []string{"Sufjan Stevens.", "James Blake.", "Big Red Machine."},
		},
		{
			Title:     "Vinyl vs streaming — do you hear a difference?",
			Content:   "I’ve been collecting vinyl for a year. Placebo or real? What’s your experience?",
			PostType:  "text",
			ImageSeed: "music-vinyl",
			Comments:  []string{"Depends on the mastering. Sometimes vinyl is better.", "I do it for the ritual.", "Streaming is fine for me."},
		},
		{
			Title:     "Best live performance you’ve seen on YouTube",
			Content:   "Links welcome. Looking for that “wish I was there” energy.",
			PostType:  "link",
			ImageSeed: "music-live",
			LinkURL:   "https://www.youtube.com/results?search_query=best+live+performance",
			Comments:  []string{"NPR Tiny Desk has so many gems.", "That Prince Super Bowl halftime.", "Queen at Wembley."},
		},
		{
			Title:     "Genre you hated until one artist changed your mind",
			Content:   "I used to think country was boring until I heard Jason Isbell.",
			PostType:  "text",
			ImageSeed: "music-genre",
			Comments:  []string{"Metal — Opeth did it.", "K-pop — BTS.", "Jazz — Kamasi Washington."},
		},
	},
	"anime": {
		{
			Title:     "Frieren — where to watch and is it worth it?",
			Content:   "Seeing it everywhere. Sub vs dub? Best place to stream?",
			PostType:  "text",
			ImageSeed: "anime-frieren",
			Comments:  []string{"Sub. Crunchyroll. 100% worth it.", "Best anime of the year.", "Dub is solid too."},
		},
		{
			Title:     "Anime with the best fight choreography",
			Content:   "Just finished Demon Slayer. What has animation that good or better?",
			PostType:  "text",
			ImageSeed: "anime-fights",
			Comments:  []string{"Jujutsu Kaisen.", "Mob Psycho 100.", "One Punch Man S1."},
		},
		{
			Title:     "Recommend an anime for someone who doesn’t like anime",
			Content:   "Friend says they don’t like “anime” but loved Arcane and Avatar. What’s a good bridge?",
			PostType:  "text",
			ImageSeed: "anime-gateway",
			Comments:  []string{"Death Note.", "Spy x Family.", "Attack on Titan."},
		},
		{
			Title:     "Best anime movie of all time?",
			Content:   "Standalone movie, not a series recap. Go.",
			PostType:  "text",
			ImageSeed: "anime-movie",
			Comments:  []string{"Spirited Away.", "Your Name.", "Akira."},
		},
		{
			Title:     "Manga that’s better than the anime adaptation",
			Content:   "Where did the anime drop the ball?",
			PostType:  "text",
			ImageSeed: "anime-manga",
			Comments:  []string{"Berserk.", "One Piece pacing.", "Tokyo Ghoul."},
		},
		{
			Title:     "Chill slice-of-life anime recommendations",
			Content:   "Need something low-stakes and cozy. Already seen Yuru Camp and Bocchi.",
			PostType:  "text",
			ImageSeed: "anime-sol",
			Comments:  []string{"Barakamon.", "Natsume’s Book of Friends.", "Mushishi."},
		},
		{
			Title:     "One Piece — worth the 1000+ episodes?",
			Content:   "I’m at episode 50. Does the pacing ever get better?",
			PostType:  "text",
			ImageSeed: "anime-onepiece",
			Comments:  []string{"Consider One Pace (fan edit).", "Manga is the way.", "It has lulls but the peaks are worth it."},
		},
		{
			Title:     "Anime with a satisfying ending",
			Content:   "So many great shows fumble the ending. Which ones stick the landing?",
			PostType:  "text",
			ImageSeed: "anime-ending",
			Comments:  []string{"Fullmetal Alchemist: Brotherhood.", "Steins;Gate.", "Code Geass."},
		},
		{
			Title:     "Best OP/ED (opening/ending) you’ve heard?",
			Content:   "Music and visuals. What’s stuck in your head?",
			PostType:  "text",
			ImageSeed: "anime-op",
			Comments:  []string{"Attack on Titan S3 OP.", "Cowboy Bebop tank!", "Unravel from Tokyo Ghoul."},
		},
		{
			Title:     "Studio Ghibli ranking — fight me",
			Content:   "My top 3: Spirited Away, Howl’s, Totoro. What’s yours?",
			PostType:  "text",
			ImageSeed: "anime-ghibli",
			Comments:  []string{"Princess Mononoke #1.", "Grave of the Fireflies is best but I can’t rewatch.", "Kiki forever."},
		},
	},
	"gaming": {
		{
			Title:     "What are you playing this weekend?",
			Content:   "I’m finally starting Elden Ring. Any tips for a Souls newbie?",
			PostType:  "text",
			ImageSeed: "gaming-weekend",
			Comments:  []string{"Don’t fight the tree sentinel early.", "Level vigor.", "Explore Limgrave first."},
		},
		{
			Title:     "Game that exceeded your expectations in 2024?",
			Content:   "Mine: Balatro. Thought it was just a poker roguelike but it’s addictive.",
			PostType:  "text",
			ImageSeed: "gaming-2024",
			Comments:  []string{"Hades 2.", "Dragon’s Dogma 2.", "Palworld (controversial but fun)."},
		},
		{
			Title:     "Best co-op game for two people on different skill levels?",
			Content:   "My partner isn’t a gamer but wants to play something together. Casual-friendly ideas?",
			PostType:  "text",
			ImageSeed: "gaming-coop",
			Comments:  []string{"It Takes Two.", "Overcooked 2.", "Stardew Valley."},
		},
		{
			Title:     "Nintendo Direct just announced a new Zelda",
			Content:   "No release date yet but the trailer looked incredible. Thoughts?",
			PostType:  "text",
			ImageSeed: "gaming-zelda",
			Comments:  []string{"Hype.", "Hope it’s not another BotW clone.", "Day one."},
		},
		{
			Title:     "Game you’ve replayed the most?",
			Content:   "I’ve done Dark Souls 1 at least 10 times. What’s your comfort replay?",
			PostType:  "text",
			ImageSeed: "gaming-replay",
			Comments:  []string{"Skyrim.", "Mass Effect trilogy.", "Resident Evil 4."},
		},
		{
			Title:     "Indie game that deserves a sequel",
			Content:   "Mine: Hollow Knight. Silksong when?!",
			PostType:  "text",
			ImageSeed: "gaming-indie",
			Comments:  []string{"Outer Wilds.", "Disco Elysium.", "Celeste."},
		},
		{
			Title:     "Best game soundtrack?",
			Content:   "I listen to video game OSTs while working. What’s your favorite?",
			PostType:  "text",
			ImageSeed: "gaming-ost",
			Comments:  []string{"NieR Automata.", "Persona 5.", "Chrono Trigger."},
		},
		{
			Title:     "PS5 vs Xbox Series X in 2025?",
			Content:   "Looking to buy my first current-gen console. Which has the better exclusives and value now?",
			PostType:  "text",
			ImageSeed: "gaming-console",
			Comments:  []string{"PS5 for exclusives.", "Xbox for Game Pass.", "Depends what you play."},
		},
		{
			Title:     "Game that made you cry",
			Content:   "No shame. Mine: The Last of Us Part II.",
			PostType:  "text",
			ImageSeed: "gaming-cry",
			Comments:  []string{"RDR2.", "Spiritfarer.", "To the Moon."},
		},
		{
			Title:     "Backlog confession",
			Content:   "How many games do you own but have never played? I’m at 200+ on Steam. No judgment.",
			PostType:  "text",
			ImageSeed: "gaming-backlog",
			Comments:  []string{"Same. Humble Bundle broke me.", "I’ve made peace with it.", "One day."},
		},
	},
	"pcgaming": {
		{
			Title:     "Baldur’s Gate 3 — mods worth installing for first playthrough?",
			Content:   "About to start. Should I go vanilla or add QoL mods?",
			PostType:  "text",
			ImageSeed: "pcgaming-bg3",
			Comments:  []string{"Vanilla first. Mod after.", "Native Camera and Party Limit Begone are safe.", "No mods, experience it pure."},
		},
		{
			Title:     "Best GPU for 1440p at ~$400?",
			Content:   "Looking to upgrade from a 1060. RT not a priority. What’s the best value right now?",
			PostType:  "text",
			ImageSeed: "pcgaming-gpu",
			Comments:  []string{"RX 7700 XT.", "Used 3070 if you can find one.", "Wait for next gen if you can."},
		},
		{
			Title:     "Steam Deck vs ROG Ally for travel?",
			Content:   "I travel a lot and want a handheld PC. Which has better battery and compatibility?",
			PostType:  "text",
			ImageSeed: "pcgaming-handheld",
			Comments:  []string{"Steam Deck for Linux and battery.", "Ally for raw power.", "Deck for ease of use."},
		},
		{
			Title:     "Cyberpunk 2077 — is it fixed now?",
			Content:   "Haven’t touched it since launch. Heard 2.0 and Phantom Liberty are great. Worth jumping back in?",
			PostType:  "text",
			ImageSeed: "pcgaming-cp77",
			Comments:  []string{"Yes. Completely different game.", "Phantom Liberty is a must.", "One of the best turnarounds."},
		},
		{
			Title:     "PC building tips for first-time builder",
			Content:   "Putting together my first build. What do you wish you’d known?",
			PostType:  "text",
			ImageSeed: "pcgaming-build",
			Comments:  []string{"Don’t cheap out on the PSU.", "Check RAM compatibility with mobo.", "Cable management as you go."},
		},
		{
			Title:     "Best mouse for FPS?",
			Content:   "Budget around $80. Prefer lightweight. Currently using a G502 and it’s too heavy.",
			PostType:  "text",
			ImageSeed: "pcgaming-mouse",
			Comments:  []string{"Logitech G Pro X Superlight.", "Razer Viper.", "Glorious Model O."},
		},
		{
			Title:     "Hollow Knight: Silksong — any news?",
			Content:   "It’s been radio silence for a while. Still hopeful for 2025?",
			PostType:  "text",
			ImageSeed: "pcgaming-silksong",
			Comments:  []string{"Team Cherry pls.", "I’ve given up on release dates.", "It’ll come when it comes."},
		},
		{
			Title:     "Game that runs surprisingly well on low-end hardware?",
			Content:   "GTX 1650 here. What have you been impressed by?",
			PostType:  "text",
			ImageSeed: "pcgaming-lowend",
			Comments:  []string{"Elden Ring is well-optimized.", "Hades.", "Vampire Survivors."},
		},
		{
			Title:     "GOG vs Steam for DRM-free preference?",
			Content:   "I like owning my games. How’s GOG’s library and client compared to Steam now?",
			PostType:  "text",
			ImageSeed: "pcgaming-gog",
			Comments:  []string{"GOG for classics, Steam for everything else.", "GOG Galaxy is fine.", "Wish more devs went DRM-free."},
		},
		{
			Title:     "Best mechanical keyboard under $100?",
			Content:   "Looking for TKL, hot-swap preferred. Recommendations?",
			PostType:  "text",
			ImageSeed: "pcgaming-kb",
			Comments:  []string{"Keychron K8.", "Royal Kludge RK87.", "Epomaker has good options."},
		},
	},
	"development": {
		{
			Title:     "Go vs Rust for a new CLI tool?",
			Content:   "Need to build a small CLI that might grow. Which would you pick and why?",
			PostType:  "text",
			ImageSeed: "dev-cli",
			Comments:  []string{"Go for speed of development.", "Rust if you care about memory safety and perf.", "Go. Simplicity wins."},
		},
		{
			Title:     "Best way to learn a new codebase?",
			Content:   "Just joined a new team. Repo is huge. How do you approach understanding it?",
			PostType:  "text",
			ImageSeed: "dev-codebase",
			Comments:  []string{"Find the entry points and trace execution.", "Read the tests.", "Ask for a walkthrough from the team."},
		},
		{
			Title:     "Docker Compose for local dev — any gotchas?",
			Content:   "Setting up a multi-service app. What do you wish you’d known about Compose?",
			PostType:  "text",
			ImageSeed: "dev-docker",
			Comments:  []string{"Use named volumes for persistence.", "Don’t run DB in Compose in prod.", "Healthchecks are your friend."},
		},
		{
			Title:     "TypeScript strict mode — enable from day one?",
			Content:   "Starting a new frontend project. Team is split on strict. What’s your take?",
			PostType:  "text",
			ImageSeed: "dev-ts",
			Comments:  []string{"Yes. Saves pain later.", "Enable gradually.", "Strict from the start."},
		},
		{
			Title:     "Recommended resources for learning system design?",
			Content:   "Preparing for interviews. Books, courses, or practice sites?",
			PostType:  "text",
			ImageSeed: "dev-systemdesign",
			Comments:  []string{"Designing Data-Intensive Applications.", "ByteByteGo on YouTube.", "Practice with real problems."},
		},
		{
			Title:     "How do you structure a monorepo?",
			Content:   "We’re moving from multiple repos to a monorepo. Any conventions or tools you recommend?",
			PostType:  "text",
			ImageSeed: "dev-monorepo",
			Comments:  []string{"Nx or Turborepo.", "Keep packages small and focused.", "Shared tooling at root."},
		},
		{
			Title:     "API versioning strategy — URL path vs header?",
			Content:   "What do you use in production and why?",
			PostType:  "text",
			ImageSeed: "dev-api",
			Comments:  []string{"Path: /v1/... Simple and explicit.", "Header for flexibility.", "Path. Easier to debug."},
		},
		{
			Title:     "Best practices for database migrations in a team?",
			Content:   "We keep stepping on each other’s migrations. How do you coordinate?",
			PostType:  "text",
			ImageSeed: "dev-migrations",
			Comments:  []string{"Numbered migrations, one per PR.", "Squash before merge.", "Review migration order in PR."},
		},
		{
			Title:     "Side project that actually shipped — what worked?",
			Content:   "I have 10 half-finished ideas. What helped you actually finish and launch something?",
			PostType:  "text",
			ImageSeed: "dev-sideproject",
			Comments:  []string{"Scope tiny. Ship in a weekend.", "Find a co-founder.", "Solve your own problem."},
		},
		{
			Title:     "Logging in production — what do you log and what do you avoid?",
			Content:   "Trying to improve observability without logging PII or secrets. What’s your checklist?",
			PostType:  "text",
			ImageSeed: "dev-logging",
			Comments:  []string{"Never log passwords or tokens.", "Structured JSON with levels.", "Request IDs for tracing."},
		},
	},
	"hardware": {
		{
			Title:     "Best CPU for gaming + light streaming in 2025?",
			Content:   "Budget around $300. AMD or Intel?",
			PostType:  "text",
			ImageSeed: "hw-cpu",
			Comments:  []string{"Ryzen 7 7800X3D for pure gaming.", "Intel 14700K if you need multi-thread.", "7800X3D is the king."},
		},
		{
			Title:     "Custom loop vs AIO for first water cooling?",
			Content:   "Want to try water cooling. Is a custom loop overkill for a 4070 + 7800X3D?",
			PostType:  "text",
			ImageSeed: "hw-water",
			Comments:  []string{"AIO is enough. Custom is for fun.", "AIO first. Custom later if you get hooked.", "Custom is a hobby, not necessity."},
		},
		{
			Title:     "Quiet case recommendations?",
			Content:   "Current case sounds like a jet. Looking for something with good airflow but quiet.",
			PostType:  "text",
			ImageSeed: "hw-case",
			Comments:  []string{"Fractal Design Define 7.", "Be Quiet! Silent Base.", "Lian Li has good options."},
		},
		{
			Title:     "NVMe vs SATA SSD for game storage?",
			Content:   "Do games actually benefit from NVMe or is SATA fine for a secondary drive?",
			PostType:  "text",
			ImageSeed: "hw-ssd",
			Comments:  []string{"NVMe for OS and main games.", "SATA is fine for bulk storage.", "Loading times improve with NVMe in some games."},
		},
		{
			Title:     "Monitor: 4K 60Hz vs 1440p 144Hz for mixed use?",
			Content:   "Gaming + work. Which would you choose?",
			PostType:  "text",
			ImageSeed: "hw-monitor",
			Comments:  []string{"1440p 144Hz for gaming focus.", "4K for productivity.", "1440p ultrawide best of both."},
		},
		{
			Title:     "PSU calculator — how much headroom do you add?",
			Content:   "Building a 4070 + 7800X3D system. 650W enough or go 750W?",
			PostType:  "text",
			ImageSeed: "hw-psu",
			Comments:  []string{"750W for headroom.", "650W is fine but 750W gives peace of mind.", "Efficiency is better at ~50% load."},
		},
		{
			Title:     "Best thermal paste application method?",
			Content:   "Pea size, X, or spread? Replacing my cooler and want to do it right.",
			PostType:  "text",
			ImageSeed: "hw-paste",
			Comments:  []string{"Pea or X. Spread can trap bubbles.", "Pea is fine for most CPUs.", "Don’t overthink it."},
		},
		{
			Title:     "RAM: 32GB vs 64GB for gaming and dev?",
			Content:   "Chrome + IDE + game. Is 32GB enough in 2025?",
			PostType:  "text",
			ImageSeed: "hw-ram",
			Comments:  []string{"32GB is enough for most.", "64GB if you run VMs or heavy IDEs.", "32GB now, upgrade later if needed."},
		},
		{
			Title:     "Used GPU — red flags when buying?",
			Content:   "Looking at a used 3080. What should I check or avoid?",
			PostType:  "text",
			ImageSeed: "hw-used",
			Comments:  []string{"Mining cards can be fine if thermal pads replaced.", "Ask for stress test results.", "Check warranty transfer."},
		},
		{
			Title:     "Desk setup for WFH + gaming?",
			Content:   "One desk for work and play. Monitor arm? Cable management tips?",
			PostType:  "text",
			ImageSeed: "hw-desk",
			Comments:  []string{"Monitor arm saves space.", "Cable raceway under desk.", "KVM switch if two PCs."},
		},
	},
	"linux": {
		{
			Title:     "Best distro for a developer coming from macOS?",
			Content:   "Used Mac for 10 years. Want to try Linux for dev. Fedora? Ubuntu? Something else?",
			PostType:  "text",
			ImageSeed: "linux-distro",
			Comments:  []string{"Fedora. Polished and up-to-date.", "Ubuntu for stability.", "Pop!_OS for NVIDIA."},
		},
		{
			Title:     "Wayland vs X11 in 2025?",
			Content:   "Is Wayland ready for daily driving? Gaming, multiple monitors, fractional scaling?",
			PostType:  "text",
			ImageSeed: "linux-wayland",
			Comments:  []string{"Wayland is fine for most.", "X11 for gaming if you have issues.", "Wayland + Nvidia still has quirks."},
		},
		{
			Title:     "How do you manage dotfiles?",
			Content:   "Just starting to version my configs. Bare repo, stow, or something else?",
			PostType:  "text",
			ImageSeed: "linux-dotfiles",
			Comments:  []string{"GNU Stow.", "Bare git repo in home.", "Chezmoi."},
		},
		{
			Title:     "Linux on the Steam Deck — what did you learn?",
			Content:   "Considering dual-booting or switching. How’s the experience for gaming and general use?",
			PostType:  "text",
			ImageSeed: "linux-gaming",
			Comments:  []string{"Proton is magic.", "Most games just work.", "Lutris for non-Steam."},
		},
		{
			Title:     "Best terminal emulator?",
			Content:   "Currently using default. Looking for something with good font rendering and tabs.",
			PostType:  "text",
			ImageSeed: "linux-terminal",
			Comments:  []string{"Alacritty.", "Kitty.", "WezTerm."},
		},
		{
			Title:     "Nvidia drivers on Linux — still a pain?",
			Content:   "Considering a 4070. Heard mixed things about Nvidia on Linux.",
			PostType:  "text",
			ImageSeed: "linux-nvidia",
			Comments:  []string{"Better than it was. Still not perfect.", "Use the proprietary driver.", "AMD is easier if you’re buying new."},
		},
		{
			Title:     "Recommended backup strategy for home server?",
			Content:   "Running a small home server. What do you use for backups?",
			PostType:  "text",
			ImageSeed: "linux-backup",
			Comments:  []string{"Borg backup.", "Restic.", "rsync to external + offsite."},
		},
		{
			Title:     "Sway vs Hyprland for tiling?",
			Content:   "Want to try a tiling Wayland compositor. Which has better documentation and stability?",
			PostType:  "text",
			ImageSeed: "linux-tiling",
			Comments:  []string{"Sway is more mature.", "Hyprland for eye candy.", "Sway for stability."},
		},
		{
			Title:     "Linux laptop for dev — what do you use?",
			Content:   "Looking for something that works well out of the box. Framework? ThinkPad?",
			PostType:  "text",
			ImageSeed: "linux-laptop",
			Comments:  []string{"ThinkPad. Great Linux support.", "Framework. Repairable.", "Dell XPS with Ubuntu."},
		},
		{
			Title:     "Docker on Linux — rootless worth the setup?",
			Content:   "Setting up a dev environment. Should I bother with rootless Docker?",
			PostType:  "text",
			ImageSeed: "linux-docker",
			Comments:  []string{"Yes. Safer.", "Rootless + rootful both work.", "Podman is rootless by default."},
		},
	},
	"ai": {
		{
			Title:     "Best open-source LLM to run locally in 2025?",
			Content:   "Have a 24GB GPU. What’s the best model for coding and general chat?",
			PostType:  "text",
			ImageSeed: "ai-llm",
			Comments:  []string{"Llama 3.1 70B quantized.", "Qwen 2.5.", "Mistral for balance."},
		},
		{
			Title:     "How are you using AI in your dev workflow?",
			Content:   "Copilot? Cursor? Custom prompts? What actually saves you time?",
			PostType:  "text",
			ImageSeed: "ai-workflow",
			Comments:  []string{"Cursor for refactors.", "Copilot for boilerplate.", "Claude for design docs."},
		},
		{
			Title:     "Stable Diffusion vs Midjourney for personal projects?",
			Content:   "Want to generate images for a game idea. Which has better quality and control?",
			PostType:  "text",
			ImageSeed: "ai-images",
			Comments:  []string{"SD for control, MJ for polish.", "ComfyUI + SD for flexibility.", "DALL-E 3 for simplicity."},
		},
		{
			Title:     "AI coding tools — do they make you a better or lazier developer?",
			Content:   "Honest opinions. Have your habits changed?",
			PostType:  "text",
			ImageSeed: "ai-debate",
			Comments:  []string{"Better. I ship faster.", "Lazier on boilerplate, more time on design.", "Both. Depends how you use it."},
		},
		{
			Title:     "Recommended resources for learning how LLMs work?",
			Content:   "Not just how to use them—how attention, training, and inference work.",
			PostType:  "text",
			ImageSeed: "ai-learn",
			Comments:  []string{"Andrej Karpathy’s videos.", "Jay Alammar’s blog.", "The Illustrated Transformer."},
		},
		{
			Title:     "Running LLMs on CPU only — viable?",
			Content:   "No GPU. Can I run something useful on a good CPU?",
			PostType:  "text",
			ImageSeed: "ai-cpu",
			Comments:  []string{"Small models (7B) with quantization.", "Slow but works.", "Ollama + llama.cpp."},
		},
		{
			Title:     "Best vector DB for RAG in a side project?",
			Content:   "Building a small RAG app. Chroma? Pinecone? Something self-hosted?",
			PostType:  "text",
			ImageSeed: "ai-rag",
			Comments:  []string{"Chroma for simplicity.", "pgvector if you have Postgres.", "Qdrant for scale."},
		},
		{
			Title:     "AI-generated code in production — would you?",
			Content:   "Assuming you review it. Would you merge AI-written code for critical paths?",
			PostType:  "text",
			ImageSeed: "ai-prod",
			Comments:  []string{"Yes, with tests.", "For boilerplate only.", "Depends on the team."},
		},
		{
			Title:     "Prompt engineering — what actually works?",
			Content:   "Beyond “be specific.” Any frameworks or tricks you use?",
			PostType:  "text",
			ImageSeed: "ai-prompts",
			Comments:  []string{"Chain of thought for reasoning.", "Few-shot examples.", "Structured output (JSON) helps."},
		},
		{
			Title:     "Multimodal models — image + text in 2025",
			Content:   "What’s the best model for “describe this screenshot” or “extract text from this image”?",
			PostType:  "text",
			ImageSeed: "ai-multimodal",
			Comments:  []string{"GPT-4V.", "Claude 3.", "Open-source: LLaVA."},
		},
	},
	"fitness": {
		{
			Title:     "Best program for building a home gym on a budget?",
			Content:   "Have space for a rack, bench, and some weights. What program do you recommend?",
			PostType:  "text",
			ImageSeed: "fitness-home",
			Comments:  []string{"Starting Strength or GZCLP.", "r/fitness wiki has good templates.", "Stronger by Science."},
		},
		{
			Title:     "How do you stay consistent with morning workouts?",
			Content:   "I always skip when I tell myself I’ll go in the morning. What worked for you?",
			PostType:  "text",
			ImageSeed: "fitness-morning",
			Comments:  []string{"Sleep in gym clothes.", "Don’t think, just go.", "After work works better for me."},
		},
		{
			Title:     "Running vs cycling for cardio?",
			Content:   "Trying to pick one to focus on. Joints are a concern.",
			PostType:  "text",
			ImageSeed: "fitness-cardio",
			Comments:  []string{"Cycling is easier on joints.", "Swimming if you have access.", "Mix both."},
		},
		{
			Title:     "Protein intake — how much is enough?",
			Content:   "I keep seeing 1g per lb bodyweight. Is that overkill for someone not competing?",
			PostType:  "text",
			ImageSeed: "fitness-protein",
			Comments:  []string{"0.7–1g per lb is the range.", "More doesn’t hurt.", "Prioritize consistency over number."},
		},
		{
			Title:     "Best YouTube channels for form and programming?",
			Content:   "Squat, deadlift, bench. Who do you trust?",
			PostType:  "text",
			ImageSeed: "fitness-yt",
			Comments:  []string{"Alan Thrall.", "Jeff Nippard.", "Squat University."},
		},
		{
			Title:     "Recovery day — complete rest or light activity?",
			Content:   "What do you do on rest days? Walk? Stretch? Nothing?",
			PostType:  "text",
			ImageSeed: "fitness-recovery",
			Comments:  []string{"Walk and stretch.", "Light yoga.", "Complete rest if sore."},
		},
		{
			Title:     "First marathon — training plan recommendations?",
			Content:   "Have a year to prepare. Never run more than a half. What plan did you use?",
			PostType:  "text",
			ImageSeed: "fitness-marathon",
			Comments:  []string{"Hal Higdon.", "Pfitzinger.", "Build base first, then a plan."},
		},
		{
			Title:     "Gym anxiety — how did you get over it?",
			Content:   "New to the gym. Feel like everyone is judging. Tips?",
			PostType:  "text",
			ImageSeed: "fitness-anxiety",
			Comments:  []string{"Nobody is watching. Really.", "Go at off-peak hours.", "Everyone started somewhere."},
		},
		{
			Title:     "Pre-workout — worth it or placebo?",
			Content:   "Considering trying pre-workout. Does it actually help or is it just caffeine?",
			PostType:  "text",
			ImageSeed: "fitness-pre",
			Comments:  []string{"Mostly caffeine. Coffee works.", "Placebo can still help.", "Try it. Some people love it."},
		},
		{
			Title:     "Best stretch routine for desk workers?",
			Content:   "Sitting 8+ hours. Hips and back are tight. What do you do?",
			PostType:  "text",
			ImageSeed: "fitness-stretch",
			Comments:  []string{"Hip flexor stretches.", "Stand and walk every hour.", "Yoga with Adriene on YouTube."},
		},
	},
	"food": {
		{
			Title:     "Best way to meal prep for the week?",
			Content:   "I always get bored by Wednesday. How do you keep it varied and actually eat what you prep?",
			PostType:  "text",
			ImageSeed: "food-mealprep",
			Comments:  []string{"Prep components, not full meals.", "Freeze half.", "Different sauces same base."},
		},
		{
			Title:     "Sourdough starter — what went wrong?",
			Content:   "Mine is on day 5 and smells like vinegar. Is that normal or did I kill it?",
			PostType:  "text",
			ImageSeed: "food-sourdough",
			Comments:  []string{"Vinegar smell can be normal. Keep feeding.", "Discard and feed 1:1:1.", "Give it more time."},
		},
		{
			Title:     "Easy weeknight dinner that isn’t pasta?",
			Content:   "I default to pasta every time. Need ideas that are fast and minimal cleanup.",
			PostType:  "text",
			ImageSeed: "food-weeknight",
			Comments:  []string{"Sheet pan chicken and veggies.", "Stir fry.", "Tacos."},
		},
		{
			Title:     "Best kitchen knife for a home cook?",
			Content:   "Don’t need a full set. One or two good knives. What do you recommend?",
			PostType:  "text",
			ImageSeed: "food-knife",
			Comments:  []string{"8\" chef's knife. Victorinox or Wüsthof.", "Kiwi knives are cheap and sharp.", "One good chef's knife is enough."},
		},
		{
			Title:     "Recipe that impressed someone you were cooking for?",
			Content:   "What’s your go-to “I want to impress” dish?",
			PostType:  "text",
			ImageSeed: "food-impress",
			Comments:  []string{"Coq au vin.", "Beef Wellington (labor intensive).", "Simple roast chicken done right."},
		},
		{
			Title:     "Instant Pot — worth the counter space?",
			Content:   "Considering one for beans and meal prep. Do you use yours enough to justify it?",
			PostType:  "text",
			ImageSeed: "food-instantpot",
			Comments:  []string{"Yes for beans and rice.", "I use it weekly.", "Pressure cooker + slow cooker in one."},
		},
		{
			Title:     "How do you make vegetables actually taste good?",
			Content:   "I want to eat more veggies but I get bored. Roasting? Seasoning?",
			PostType:  "text",
			ImageSeed: "food-veggies",
			Comments:  []string{"Roast with olive oil and salt.", "Don’t boil. Roast or sauté.", "Add garlic and lemon."},
		},
		{
			Title:     "Best cookbook for beginners?",
			Content:   "Someone who can follow a recipe but wants to understand why. Recommendations?",
			PostType:  "text",
			ImageSeed: "food-cookbook",
			Comments:  []string{"Salt Fat Acid Heat.", "The Food Lab.", "How to Cook Everything."},
		},
		{
			Title:     "Coffee at home — grinder and method?",
			Content:   "Tired of spending $6 on coffee. What’s a good home setup for pour-over or French press?",
			PostType:  "text",
			ImageSeed: "food-coffee",
			Comments:  []string{"Baratza Encore + V60.", "Any burr grinder + French press.", "Don’t skip the grinder."},
		},
		{
			Title:     "Restaurant dish you’ve successfully recreated at home?",
			Content:   "What was the trick? Mine: Cacio e Pepe. Lots of pasta water and low heat.",
			PostType:  "text",
			ImageSeed: "food-recreate",
			Comments:  []string{"Pad Thai. Tamarind is key.", "Chicken tikka masala.", "French onion soup."},
		},
	},
}
